### ISSUE TITLE
GET /user is returning null fields

### ISSUE THREAD

**Issue by mandriv** [lejhy/Miotag#1]
Here's the screenshot confirming that the `firstName` and `lastName` of the user are specified:
<img width="1339" alt="Screenshot 2020-01-15 at 20 35 49" src="https://user-images.githubusercontent.com/12617730/72469102-a476ce80-37d6-11ea-98b2-eaa6d7b0c9b9.png">
However, when I hit
`GET /user` I receive null fields like so:
```
id  16
firstName  null
lastName  null
email  aaa@email.com
password  null
```

**Comment by lejhy** [comment]
Will investigate 😊

**Comment by mandriv** [comment]
Same issue occurs on `GET /relations` - no `firstName` or `lastName`
